from enum import StrEnum


class ErrorReason(StrEnum):
    APP_ERROR = "app_error"

    AUTHENTICATION_REQUIRED = "authentication_required"
    EMAIL_ALREADY_EXISTS = "email_already_exists"
    INVALID_CREDENTIALS = "invalid_credentials"
    INVALID_REFRESH_TOKEN = "invalid_refresh_token"
    INVALID_TOKEN = "invalid_token"
    INVALID_TOKEN_PAYLOAD = "invalid_token_payload"
    INVALID_TOKEN_TYPE = "invalid_token_type"
    MISSING_AUTHORIZATION_TOKEN = "missing_authorization_token"
    USER_NOT_FOUND = "user_not_found"
    SITE_PERMISSION_DENIED = "site_permission_denied"

    CANNOT_REMOVE_SELF_FROM_ROOM = "cannot_remove_self_from_room"
    INVALID_ROOM_ID = "invalid_room_id"
    INVALID_ROOM_MEMBER_ROLE = "invalid_room_member_role"
    JOIN_REQUEST_ALREADY_HANDLED = "join_request_already_handled"
    JOIN_REQUEST_NOT_FOUND = "join_request_not_found"
    JOIN_REQUEST_TARGET_ACTION_FORBIDDEN = "join_request_target_action_forbidden"
    MISSING_ROOM_ID = "missing_room_id"
    OWNER_CANNOT_BE_REMOVED_FROM_ROOM = "owner_cannot_be_removed_from_room"
    OWNER_CANNOT_LEAVE_ROOM = "owner_cannot_leave_room"
    OWNER_ROLE_CANNOT_BE_CHANGED = "owner_role_cannot_be_changed"
    PENDING_JOIN_REQUEST_ALREADY_EXISTS = "pending_join_request_already_exists"
    ROOM_ENTER_FORBIDDEN = "room_enter_forbidden"
    ROOM_MEMBER_NOT_FOUND = "room_member_not_found"
    ROOM_NOT_ACCEPTING_JOIN_REQUESTS = "room_not_accepting_join_requests"
    ROOM_NOT_ENTERED = "room_not_entered"
    ROOM_NOT_FOUND = "room_not_found"
    ROOM_PERMISSION_DENIED = "room_permission_denied"
    ROOM_SETTINGS_NOT_FOUND = "room_settings_not_found"
    USER_ALREADY_ROOM_MEMBER = "user_already_room_member"

    PAGINATION_NOT_ALLOWED_WITH_ALL = "pagination_not_allowed_with_all"

    MESSAGE_NOT_FOUND = "message_not_found"
    NOTIFICATION_NOT_FOUND = "notification_not_found"
    NOTIFICATION_PERMISSION_DENIED = "notification_permission_denied"
    NOTIFICATION_RELATED_FIELDS_INCOMPLETE = "notification_related_fields_incomplete"

    INVALID_HEARTBEAT_ACTION = "invalid_heartbeat_action"
    INVALID_INTEGER_FIELD = "invalid_integer_field"
    INVALID_NUMBER_FIELD = "invalid_number_field"
    INVALID_STRING_FIELD = "invalid_string_field"
    INVALID_WEBSOCKET_PAYLOAD = "invalid_websocket_payload"
    REQUEST_VALIDATION_FAILED = "request_validation_failed"
    UNSUPPORTED_CLIENT_MESSAGE_TYPE = "unsupported_client_message_type"
    UNSUPPORTED_COMMAND_ACTION = "unsupported_command_action"
    UNSUPPORTED_ROOM_COMMAND_ACTION = "unsupported_room_command_action"

    FEEDBACK_NOT_FOUND = "feedback_not_found"
    FEEDBACK_PERMISSION_DENIED = "feedback_permission_denied"
